//! Physical key chords lowered to command-stream bindings.
//!
//! ADR 0014: keybindings are `bind` lines. [`DEFAULT_BINDS`] is the cfg of
//! defaults (pi parity), executed before the user's `config.cfg`;
//! [`PI_ACTIONS`] is the migration table from pi's action ids to the console
//! command each default binds.

pub mod config;

/// Default `bind` script, executed before `config.cfg`.
pub const DEFAULT_BINDS: &str = include_str!("default.cfg");

/// Name of the default bind cfg as reported in command-stream provenance.
pub const DEFAULT_BINDS_NAME: &str = "default-binds.cfg";

/// pi app keybinding id → console command bound by [`DEFAULT_BINDS`].
///
/// Session-picker-local keys (`app.session.togglePath` …) and tree-selector
/// folds are panel chords, lowered by `omp_chat::overlays::PanelAction`
/// inside the open panel rather than bound globally, so they are absent; a
/// migrated `keybindings.toml` entry for one is dropped rather than bound
/// to a no-op.
pub const PI_ACTIONS: &[(&str, &str)] = &[
	("app.interrupt", "cl_interrupt"),
	("app.clear", "cl_clear"),
	("app.exit", "cl_exit"),
	("app.suspend", "cl_suspend"),
	("app.display.reset", "cl_display_reset"),
	("app.thinking.cycle", "cl_thinking_cycle"),
	("app.thinking.toggle", "toggle cl_showthinking"),
	("app.model.cycleForward", "cl_model_cycle"),
	("app.model.cycleBackward", "cl_model_cycle back"),
	("app.model.select", "cl_model_select"),
	("app.model.selectTemporary", "cl_model_select session"),
	("app.tools.expand", "toggle cl_tools_expanded"),
	("app.tools.toggleVisibility", "toggle cl_showtools"),
	("app.editor.external", "cl_editor_external"),
	("app.message.followUp", "cl_followup"),
	("app.retry", "cl_retry"),
	("app.plan.toggle", "cl_plan_toggle"),
	("app.history.search", "cl_history_search"),
	("app.message.dequeue", "cl_dequeue"),
	("app.clipboard.pasteImage", "cl_paste_image"),
	("app.clipboard.pasteTextRaw", "cl_paste_raw"),
	("app.clipboard.copyLine", "cl_copy_line"),
	("app.clipboard.copyPrompt", "cl_copy_prompt"),
	("app.agents.hub", "agents"),
	("app.session.observe", "hub"),
	("app.session.new", "new"),
	("app.session.tree", "tree"),
	("app.session.fork", "fork"),
	("app.session.resume", "resume"),
	("app.stt.toggle", "cl_stt_toggle"),
	("app.live.toggle", "live"),
];

/// Drops the bare `unbindall` reset that the pre-baseline `dump` wrote at the
/// top of every generated cfg. It was a serializer preamble, never a user's
/// intent, and with defaults now seeded from [`DEFAULT_BINDS`] it would erase
/// them. A hand-written `unbindall` followed by `bind` lines is kept.
#[must_use]
pub fn migrate_generated_preamble(script: &str) -> String {
	let generated = script
		.lines()
		.next()
		.is_some_and(|line| line.starts_with("// generated by omp-con dump"));
	if !generated {
		return script.to_owned();
	}
	let mut lines = script.lines().peekable();
	let mut out = String::with_capacity(script.len());
	while let Some(line) = lines.next() {
		if line.trim() == "unbindall"
			&& !lines
				.peek()
				.is_some_and(|next| next.trim_start().starts_with("bind "))
		{
			continue;
		}
		out.push_str(line);
		out.push('\n');
	}
	out
}

/// Console command for a pi keybinding id, when omp implements it.
#[must_use]
pub fn pi_action_command(action: &str) -> Option<&'static str> {
	PI_ACTIONS
		.iter()
		.find_map(|(id, command)| (*id == action).then_some(*command))
}
