//! Harness-owned dynamic devices for media generation and `AutoQA` reports.

use std::{
	collections::BTreeMap,
	error,
	fmt::{self, Display},
	fs::{self, OpenOptions},
	io,
	path::{Component, Path, PathBuf},
	sync::Arc,
	time::{SystemTime, UNIX_EPOCH},
};

use async_stream::stream;
use async_trait::async_trait;
use futures::Stream;
use omp_core::{ArtifactUrl, Str, sf};
use omp_proto::{
	inference::v1::{self as inference_pb, generate_image_request, value},
	thread::v1::{self as thread_pb, blob},
};
use omp_storage::telemetry_index::{StoredIssue, TelemetryIndex};
use omp_tool::{
	Abort, ArgIssue, ArgIssueKind, CommitError, Constraint, DocEffects, Effects, Ev, IncomingParams,
	InferenceEffects, ParamError, Part, PromptCaps, Rev, Tool, ToolSpec, ToolTerminal,
};
use omp_tools::ask;
use omp_voice::audio::PlaybackStream;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use tokio_util::sync::CancellationToken;

use super::{
	blobs::{BlobError, BlobHost},
	search_backend::SearchBridgeHost,
};

/// Production ask-dialog vocalizer over the application inference facade.
pub struct AskVocalizer {
	backend: Arc<SearchBridgeHost>,
}

#[async_trait]
/// Synthesizes and plays one complete dialog through local Kokoro by default.
#[async_trait]
impl omp_tools::ask::AskVocalizer for AskVocalizer {
	async fn speak(
		&self,
		lines: &[omp_tools::ask::SpokenLine],
		cancellation: CancellationToken,
	) -> Result<(), ask::Fault> {
		if cancellation.is_cancelled() || lines.is_empty() {
			return Ok(());
		}
		let mut text = String::new();
		for line in lines {
			if !text.is_empty() {
				text.push_str(". ");
			}
			text.push_str(line.text.as_str());
		}
		let request = inference_pb::SpeakRequest {
			model: "kokoro".to_owned(),
			text,
			voice: "af_heart".to_owned(),
			encoding: inference_pb::AudioEncoding::Pcm16 as i32,
			sample_rate_hz: Some(24_000),
			speed: None,
			instructions: String::new(),
			clone: None,
			props: None,
		};
		let audio = tokio::select! {
			biased;
			() = cancellation.cancelled() => {
				return Err(omp_tools::ask::Fault::Presenter {
					message: sf!("ask speech was cancelled"),
				});
			},
			audio = self.backend.speak(request) => audio.map_err(|error| {
				omp_tools::ask::Fault::Presenter { message: error.message }
			})?,
		};
		if audio.len() % 2 != 0 {
			return Err(ask::Fault::Presenter {
				message: sf!("ask speech returned malformed PCM16 audio"),
			});
		}
		let samples = audio
			.chunks_exact(2)
			.map(|sample| f32::from(i16::from_le_bytes([sample[0], sample[1]])) / f32::from(i16::MAX))
			.collect::<Vec<_>>();
		let mut playback = PlaybackStream::start(24_000)
			.map_err(|error| ask::Fault::Presenter { message: Str::from(error.to_string()) })?;
		playback
			.writer()
			.and_then(|writer| writer.write_owned(samples))
			.map_err(|error| ask::Fault::Presenter { message: Str::from(error.to_string()) })?;
		tokio::select! {
			biased;
			() = cancellation.cancelled() => {
				let _ = playback.abort();
				Err(omp_tools::ask::Fault::Presenter {
					message: sf!("ask speech was cancelled"),
				})
			},
			result = playback.drain() => result.map_err(|error| {
				omp_tools::ask::Fault::Presenter { message: Str::from(error.to_string()) }
			}),
		}
	}
}

/// Creates the production ask-dialog vocalizer.
pub(crate) fn ask_vocalizer(
	backend: Arc<SearchBridgeHost>,
) -> Arc<dyn omp_tools::ask::AskVocalizer> {
	Arc::new(AskVocalizer { backend })
}
/// Media generation arguments. Each device validates its required text field.
#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
#[serde(deny_unknown_fields)]
pub struct MediaParams {
	/// Image prompt, either plain text or a provider-neutral structured object.
	pub prompt:       Option<Value>,
	/// Speech text, required by `tts`.
	pub text:         Option<Str>,
	/// Requested provider, or the configured fallback order when absent.
	pub provider:     Option<Str>,
	/// Image aspect ratio such as `1:1` or `16:9`.
	pub aspect_ratio: Option<Str>,
	/// Optional source image artifact for image-to-image generation.
	pub input_image:  Option<Str>,
	/// Voice identifier for speech synthesis.
	pub voice:        Option<Str>,
	/// Explicit provider voice ID; takes precedence over `voice`.
	pub voice_id:     Option<Str>,
	/// BCP-47 language hint for speech synthesis.
	pub language:     Option<Str>,
	/// Requested output sample rate in hertz.
	pub sample_rate:  Option<u32>,
	/// Requested encoded bit rate in bits per second.
	pub bit_rate:     Option<u32>,
	/// Requested output format.
	pub format:       Option<Str>,
	/// Optional workspace-relative file receiving the generated bytes
	/// atomically.
	pub output_path:  Option<Str>,
}

/// A generated media artifact. Unavailable backends never fabricate one.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MediaPayload {
	/// Content-addressed artifact id.
	pub artifact_id: Str,
	/// Produced MIME type.
	pub media_type:  Str,
	/// Workspace-relative output path when file output was requested.
	pub output_path: Option<Str>,
}

/// Stable structured media backend failure.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct MediaFault {
	/// Machine-readable failure category.
	pub code:    Str,
	/// Backend that could not serve the request.
	pub backend: Str,
	/// Human-readable explanation.
	pub message: Str,
}

impl Display for MediaFault {
	fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
		write!(formatter, "{}: {}", self.code, self.message)
	}
}
impl error::Error for MediaFault {}

/// Media devices do not currently stream previews.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum MediaUpdate {}

#[derive(Clone, Copy)]
enum MediaKind {
	Image,
	Speech,
}

/// Dyn-mounted media generator.
pub struct MediaDevice {
	spec:    ToolSpec,
	kind:    MediaKind,
	backend: Arc<SearchBridgeHost>,
	blobs:   BlobHost,
	root:    PathBuf,
}

/// Creates the `image_gen@1` dynamic device.
pub fn image_gen(backend: Arc<SearchBridgeHost>, blobs: BlobHost, root: PathBuf) -> MediaDevice {
	media_device(
		"image_gen",
		"Generates images from structured prompts with provider, aspect-ratio, and format routing.",
		MediaKind::Image,
		backend,
		blobs,
		root,
	)
}

/// Creates the `tts@1` dynamic device.
pub fn tts(backend: Arc<SearchBridgeHost>, blobs: BlobHost, root: PathBuf) -> MediaDevice {
	media_device(
		"tts",
		"Synthesizes speech with local Kokoro or a configured remote voice backend.",
		MediaKind::Speech,
		backend,
		blobs,
		root,
	)
}

fn media_device(
	name: &'static str,
	description: &'static str,
	kind: MediaKind,
	backend: Arc<SearchBridgeHost>,
	blobs: BlobHost,
	root: PathBuf,
) -> MediaDevice {
	MediaDevice {
		spec: ToolSpec {
			name:            sf!(name),
			rev:             Rev { family: Default::default(), n: 1 },
			description:     sf!(description),
			schema:          omp_tool::schema::<MediaParams>(),
			constraint:      Constraint::Schema {
				priority:       100,
				on_unsupported: omp_tool::Fallback::Unspecified,
			},
			effects:         Effects {
				documents: Some(DocEffects { read: true, write_globs: Arc::from([sf!("**")]) }),
				exec:      None,
				inference: Some(InferenceEffects { max_requests: 1, max_usd: Default::default() }),
				desktop:   None,
				subagents: 0,
			},
			projection_code: omp_tool::native_projection_code(
				env!("CARGO_PKG_NAME"),
				env!("CARGO_PKG_VERSION"),
				include_bytes!("media_devices.rs"),
			)
			.into_bytes(),
		},
		kind,
		backend,
		blobs,
		root,
	}
}

impl MediaDevice {
	async fn generate_image(&self, params: &MediaParams) -> Result<MediaPayload, MediaFault> {
		let prompt = match params.prompt.as_ref().expect("validated image prompt") {
			Value::String(prompt) => prompt.clone(),
			structured => serde_json::to_string(structured).expect("structured prompt serializes"),
		};
		let input_images = params
			.input_image
			.as_ref()
			.map(|path| {
				let bytes = fs::read(path.as_str()).map_err(media_io_fault)?;
				Ok(thread_pb::Blob {
					hash:   bytes::Bytes::copy_from_slice(omp_core::Hash32::sum(&bytes).as_bytes()),
					mime:   "application/octet-stream".to_owned(),
					size:   bytes.len() as u64,
					inline: bytes.into(),
					detail: blob::Detail::Original as i32,
				})
			})
			.into_iter()
			.collect::<Result<Vec<_>, MediaFault>>()?;
		let request = inference_pb::GenerateImageRequest {
			model: params.provider.as_deref().unwrap_or_default().to_owned(),
			prompt,
			n: 1,
			aspect_ratio: aspect_ratio(params.aspect_ratio.as_deref())?,
			size: None,
			quality: generate_image_request::Quality::Medium as i32,
			format: image_format(params.format.as_deref())?,
			background: generate_image_request::Background::Unspecified as i32,
			compression: None,
			seed: None,
			input_images,
			props: None,
		};
		let mut images = self
			.backend
			.generate_image(request)
			.await
			.map_err(media_backend_fault)?;
		let image = images.drain(..).next().ok_or_else(|| {
			media_fault("image_empty", "inference", "image generation returned no artifact")
		})?;
		let artifact_id = store_blob(&self.blobs, &image)?;
		Ok(MediaPayload {
			artifact_id,
			media_type: Str::new(if image.mime.is_empty() {
				"image/png"
			} else {
				&image.mime
			}),
			output_path: None,
		})
	}

	async fn synthesize_speech(&self, params: &MediaParams) -> Result<MediaPayload, MediaFault> {
		let format = params.format.as_deref().unwrap_or("wav");
		let request = inference_pb::SpeakRequest {
			model:          params.provider.as_deref().unwrap_or("kokoro").to_owned(),
			text:           params
				.text
				.as_deref()
				.expect("validated speech text")
				.to_owned(),
			voice:          params
				.voice_id
				.as_deref()
				.or(params.voice.as_deref())
				.unwrap_or("af_heart")
				.to_owned(),
			encoding:       audio_encoding(format)?,
			sample_rate_hz: params.sample_rate,
			speed:          None,
			instructions:   params
				.language
				.as_deref()
				.map_or_else(String::new, |language| format!("Speak in {language}.")),
			clone:          None,
			props:          params.bit_rate.map(|bit_rate| inference_pb::ValueMap {
				fields: BTreeMap::from([("audio/bit_rate".to_owned(), inference_pb::Value {
					kind: Some(value::Kind::Uint(u64::from(bit_rate))),
				})]),
			}),
		};
		let audio = self
			.backend
			.speak(request)
			.await
			.map_err(media_backend_fault)?;
		let id = self.blobs.put(&audio).map_err(media_blob_fault)?;
		let output_path = params
			.output_path
			.as_deref()
			.map(|path| write_media_output(&self.root, path, &audio))
			.transpose()?;
		Ok(MediaPayload {
			artifact_id: Str::new(ArtifactUrl::from_digest(id.hash).as_str()),
			media_type: Str::new(match format {
				"mp3" => "audio/mpeg",
				"wav" => "audio/wav",
				"pcm16" => "audio/L16",
				"opus" => "audio/opus",
				"aac" => "audio/aac",
				"flac" => "audio/flac",
				_ => unreachable!("validated audio format"),
			}),
			output_path,
		})
	}
}
fn write_media_output(root: &Path, authored: &str, bytes: &[u8]) -> Result<Str, MediaFault> {
	let path = Path::new(authored);
	if path.as_os_str().is_empty()
		|| path.components().any(|component| {
			matches!(component, Component::ParentDir | Component::RootDir | Component::Prefix(_))
		}) {
		return Err(media_fault(
			"invalid_output_path",
			"filesystem",
			"output_path must be workspace-relative and contained",
		));
	}
	let root = root.canonicalize().map_err(media_io_fault)?;
	let target = root.join(path);
	let parent = target.parent().ok_or_else(|| {
		media_fault("invalid_output_path", "filesystem", "output_path has no parent")
	})?;
	let canonical_parent = parent.canonicalize().map_err(media_io_fault)?;
	if !canonical_parent.starts_with(&root) {
		return Err(media_fault(
			"invalid_output_path",
			"filesystem",
			"output_path escapes the workspace",
		));
	}
	let file_name = target.file_name().ok_or_else(|| {
		media_fault("invalid_output_path", "filesystem", "output_path has no file name")
	})?;
	let temporary = canonical_parent.join(format!(
		".{}.omp-media-{}-{}",
		file_name.to_string_lossy(),
		std::process::id(),
		now_ms()
	));
	let write_result = (|| -> io::Result<()> {
		use std::io::Write as _;
		let mut file = OpenOptions::new()
			.write(true)
			.create_new(true)
			.open(&temporary)?;
		file.write_all(bytes)?;
		file.sync_all()?;
		fs::rename(&temporary, &target)
	})();
	if let Err(error) = write_result {
		let _ = fs::remove_file(&temporary);
		return Err(media_io_fault(error));
	}
	Ok(Str::new(authored))
}

impl Tool for MediaDevice {
	type Fault = MediaFault;
	type Params = MediaParams;
	type Payload = MediaPayload;
	type Update = MediaUpdate;

	fn spec(&self) -> &ToolSpec {
		&self.spec
	}

	fn call<'c>(
		&'c self,
		mut incoming: IncomingParams<'c>,
	) -> impl Stream<Item = Ev<MediaUpdate, MediaPayload, MediaFault>> + Send + 'c {
		stream! {
			let params = match incoming.whole::<MediaParams>().await {
				Ok(params) => params,
				Err(error) => { yield media_param_event(error); return; },
			};
			let valid = match self.kind {
				MediaKind::Image => params.prompt.as_ref().is_some_and(|prompt| match prompt {
					Value::String(text) => !text.trim().is_empty(),
					Value::Object(fields) => !fields.is_empty(),
					_ => false,
				}),
				MediaKind::Speech => params.text.as_deref().is_some_and(|text| !text.trim().is_empty()),
			};
			if !valid {
				let field = match self.kind {
					MediaKind::Image => "prompt",
					MediaKind::Speech => "text",
				};
				yield media_done(Err(MediaFault {
					code: sf!("invalid_media_request"),
					backend: sf!("none"),
					message: sf!("{field} must not be empty"),
				}));
				return;
			}
			if let Err(error) = incoming.interruptable().committed().await {
				yield media_commit_event(error);
				return;
			}
			let result = match self.kind {
				MediaKind::Image => self.generate_image(&params).await,
				MediaKind::Speech => self.synthesize_speech(&params).await,
			};
			yield media_done(result);
		}
	}

	fn prompt(&self, view: Result<&MediaPayload, &MediaFault>, _: &PromptCaps) -> Vec<Part> {
		vec![Part::Text {
			text: match view {
				Ok(payload) => Str::from(format!(
					"Generated {} artifact {}",
					payload.media_type, payload.artifact_id
				)),
				Err(fault) => {
					Str::from(serde_json::to_string(fault).unwrap_or_else(|_| fault.to_string()))
				},
			},
		}]
	}
}

/// Translates provider-neutral media vocabulary into the canonical inference
/// wire.
fn aspect_ratio(value: Option<&str>) -> Result<i32, MediaFault> {
	Ok(match value.unwrap_or("1:1") {
		"1:1" => 1,
		"16:9" => 2,
		"9:16" => 3,
		"4:3" => 4,
		"3:4" => 5,
		"3:2" => 6,
		"2:3" => 7,
		"21:9" => 8,
		_ => return Err(media_fault("invalid_aspect_ratio", "image", "unsupported aspect ratio")),
	})
}

fn image_format(value: Option<&str>) -> Result<i32, MediaFault> {
	Ok(match value.unwrap_or("png") {
		"png" => generate_image_request::Format::Png as i32,
		"webp" => generate_image_request::Format::Webp as i32,
		"jpeg" | "jpg" => generate_image_request::Format::Jpeg as i32,
		_ => return Err(media_fault("invalid_image_format", "image", "unsupported image format")),
	})
}

fn audio_encoding(value: &str) -> Result<i32, MediaFault> {
	Ok(match value {
		"mp3" => inference_pb::AudioEncoding::Mp3 as i32,
		"pcm16" => inference_pb::AudioEncoding::Pcm16 as i32,
		"wav" => inference_pb::AudioEncoding::Wav as i32,
		"opus" => inference_pb::AudioEncoding::Opus as i32,
		"aac" => inference_pb::AudioEncoding::Aac as i32,
		"flac" => inference_pb::AudioEncoding::Flac as i32,
		_ => return Err(media_fault("invalid_audio_format", "speech", "unsupported audio format")),
	})
}

fn store_blob(blobs: &BlobHost, blob: &thread_pb::Blob) -> Result<Str, MediaFault> {
	let hash = if blob.inline.is_empty() {
		<[u8; 32]>::try_from(blob.hash.as_ref()).map_err(|_| {
			media_fault("invalid_image_artifact", "inference", "image artifact has no bytes or digest")
		})?
	} else {
		blobs.put(&blob.inline).map_err(media_blob_fault)?.hash
	};
	Ok(Str::new(ArtifactUrl::from_digest(hash).as_str()))
}

fn media_fault(code: &'static str, backend: &'static str, message: &'static str) -> MediaFault {
	MediaFault {
		code:    Str::new_static(code),
		backend: Str::new_static(backend),
		message: Str::new_static(message),
	}
}

fn media_backend_fault(error: omp_tools::web_search::BackendError) -> MediaFault {
	MediaFault { code: error.code, backend: sf!("inference"), message: error.message }
}

fn media_blob_fault(error: BlobError) -> MediaFault {
	MediaFault {
		code:    sf!("media_artifact_failed"),
		backend: sf!("blob"),
		message: Str::new(error.to_string()),
	}
}

fn media_io_fault(error: io::Error) -> MediaFault {
	MediaFault {
		code:    sf!("media_input_failed"),
		backend: sf!("filesystem"),
		message: Str::new(error.to_string()),
	}
}

/// Arguments accepted by `report_issue@1`.
#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ReportParams {
	/// Session filing the report.
	pub session_id: Str,
	/// Device whose structured result was inconsistent.
	pub device:     Str,
	/// Observed device revision, required for exact `name@rev` attribution.
	pub rev:        Str,
	/// Structured verdict over the device result.
	pub verdict:    Value,
}

/// Durable `AutoQA` filing result.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct ReportPayload {
	/// Stable issue identifier.
	pub issue_id: Str,
	/// Exact reported `name@rev` identity.
	pub target:   Str,
	/// Exact target revision fenced by a later consent decision.
	pub revision: Str,
	/// Redacted summary suitable for an explicit consent surface.
	pub summary:  Str,
	/// Firehose event kind written beside the issue.
	pub kind:     Str,
}

/// Dyn-mounted `AutoQA` issue recorder.
pub struct ReportIssue {
	spec:  ToolSpec,
	store: Arc<TelemetryIndex>,
}

/// Creates `report_issue@1` over the project `AutoQA` store.
pub fn report_issue(store: Arc<TelemetryIndex>) -> ReportIssue {
	ReportIssue {
		spec: ToolSpec {
			name:            sf!("report_issue"),
			rev:             Rev { family: Default::default(), n: 1 },
			description:     sf!(
				"Records a structured AutoQA verdict against an exact device revision in the durable \
				 local issue store.",
			),
			schema:          omp_tool::schema::<ReportParams>(),
			constraint:      Constraint::Schema {
				priority:       255,
				on_unsupported: omp_tool::Fallback::Unspecified,
			},
			effects:         Effects::empty(),
			projection_code: omp_tool::native_projection_code(
				env!("CARGO_PKG_NAME"),
				env!("CARGO_PKG_VERSION"),
				include_bytes!("media_devices.rs"),
			)
			.into_bytes(),
		},
		store,
	}
}

impl Tool for ReportIssue {
	type Fault = MediaFault;
	type Params = ReportParams;
	type Payload = ReportPayload;
	type Update = MediaUpdate;

	fn spec(&self) -> &ToolSpec {
		&self.spec
	}

	fn call<'c>(
		&'c self,
		mut incoming: IncomingParams<'c>,
	) -> impl Stream<Item = Ev<MediaUpdate, ReportPayload, MediaFault>> + Send + 'c {
		stream! {
			let params = match incoming.whole::<ReportParams>().await {
				Ok(params) => params,
				Err(error) => { yield report_param_event(error); return; },
			};
			if params.session_id.trim().is_empty() || params.device.trim().is_empty() || params.rev.trim().is_empty() || !params.verdict.is_object() {
				yield report_done(Err(MediaFault { code: sf!("invalid_issue_report"), backend: sf!("autoqa"), message: sf!("session_id, device, and rev are required and verdict must be an object") }));
				return;
			}
			if let Err(error) = incoming.interruptable().committed().await {
				yield report_commit_event(error);
				return;
			}
			let now = now_ms();
			let fingerprint = serde_json::json!({
				"session_id": params.session_id,
				"device": params.device,
				"rev": params.rev,
				"verdict": params.verdict,
			})
			.to_string();
			let issue_id = sf!(
				"qa-{}",
				omp_core::Hash32::sum(fingerprint.as_bytes()).to_hex()
			);
			let encoded = serde_json::json!({
				"issue_id": issue_id,
				"device": params.device,
				"rev": params.rev,
				"verdict": params.verdict,
			});
			let redacted = omp_observability::redact::redact_sensitive_credentials(&encoded.to_string());
			let payload_len = match u32::try_from(redacted.len()) {
				Ok(length) => length,
				Err(_) => {
					yield report_done(Err(MediaFault {
						code: sf!("autoqa_payload_too_large"),
						backend: sf!("autoqa"),
						message: sf!("AutoQA payload exceeds the durable frame limit"),
					}));
					return;
				},
			};
			let payload_offset = match self.store.append(
				params.session_id.as_str(),
				"issue_report",
				now,
				redacted.as_bytes(),
			) {
				Ok(offset) => offset.0,
				Err(error) => {
					yield report_done(Err(store_fault(error.to_string())));
					return;
				},
			};
			let issue = StoredIssue {
				id: issue_id.clone(),
				session_id: params.session_id.clone(),
				device: params.device.clone(),
				rev: Some(params.rev.clone()),
				consent: sf!("local_only"),
				created_at_ms: now,
				payload_offset,
				payload_len,
				consent_revision: None,
				attempt_count: 0,
				next_attempt_at_ms: 0,
				terminal: false,
				remote_ack: None,
			};
			if let Err(error) = self.store.store_issue(&issue) {
				yield report_done(Err(store_fault(error.to_string())));
				return;
			}
			let target = format!("{}@{}", issue.device, params.rev);
			yield report_done(Ok(ReportPayload {
				issue_id,
				target: Str::from(target),
				revision: params.rev,
				summary: sf!("A redacted AutoQA report is ready for optional delivery."),
				kind: sf!("issue_report"),
			}));
		}
	}

	fn prompt(&self, view: Result<&ReportPayload, &MediaFault>, _: &PromptCaps) -> Vec<Part> {
		vec![Part::Text {
			text: match view {
				Ok(payload) => {
					Str::from(format!("Filed AutoQA issue {} for {}.", payload.issue_id, payload.target))
				},
				Err(fault) => {
					Str::from(serde_json::to_string(fault).unwrap_or_else(|_| fault.to_string()))
				},
			},
		}]
	}
}

fn now_ms() -> u64 {
	SystemTime::now()
		.duration_since(UNIX_EPOCH)
		.unwrap_or_default()
		.as_millis()
		.try_into()
		.unwrap_or(u64::MAX)
}
fn store_fault(message: String) -> MediaFault {
	MediaFault {
		code:    sf!("autoqa_store_failed"),
		backend: sf!("sqlite"),
		message: Str::from(message),
	}
}
const fn media_done(
	result: Result<MediaPayload, MediaFault>,
) -> Ev<MediaUpdate, MediaPayload, MediaFault> {
	Ev::Done(ToolTerminal::Done { result, useless: false })
}
const fn report_done(
	result: Result<ReportPayload, MediaFault>,
) -> Ev<MediaUpdate, ReportPayload, MediaFault> {
	Ev::Done(ToolTerminal::Done { result, useless: false })
}
fn media_param_event(error: ParamError) -> Ev<MediaUpdate, MediaPayload, MediaFault> {
	map_param(error)
}
fn report_param_event(error: ParamError) -> Ev<MediaUpdate, ReportPayload, MediaFault> {
	map_param(error)
}
fn media_commit_event(error: CommitError) -> Ev<MediaUpdate, MediaPayload, MediaFault> {
	map_commit(error)
}
fn report_commit_event(error: CommitError) -> Ev<MediaUpdate, ReportPayload, MediaFault> {
	map_commit(error)
}
fn map_param<U, P, F>(error: ParamError) -> Ev<U, P, F> {
	match error {
		ParamError::Args(issue) => Ev::Args(*issue),
		ParamError::Interrupted(interrupt) => {
			Ev::Aborted(Abort::Interrupted { reason: interrupt.reason })
		},
		ParamError::Protocol(message) => Ev::Args(protocol_issue(message)),
	}
}
fn map_commit<U, P, F>(error: CommitError) -> Ev<U, P, F> {
	match error {
		CommitError::Aborted => Ev::Aborted(Abort::InputDropped),
		CommitError::Interrupted(interrupt) => {
			Ev::Aborted(Abort::Interrupted { reason: interrupt.reason })
		},
		CommitError::Protocol(message) => Ev::Args(protocol_issue(message)),
	}
}
fn protocol_issue(message: Str) -> ArgIssue {
	ArgIssue {
		path:     Vec::new(),
		expected: sf!("one committed JSON argument object"),
		kind:     ArgIssueKind::Protocol,
		example:  None,
		found:    Some(message),
	}
}
#[cfg(test)]
mod tests {
	use tempfile::tempdir;

	use super::*;

	#[test]
	fn report_schema_is_closed_and_accepts_structured_verdicts() {
		assert!(
			serde_json::from_value::<ReportParams>(
				serde_json::json!({"session_id":"s","device":"read","rev":"2","verdict":{"ok":false}})
			)
			.is_ok()
		);
		assert!(
			serde_json::from_value::<ReportParams>(
				serde_json::json!({"session_id":"s","device":"read","rev":"2","verdict":{},"extra":true})
			)
			.is_err()
		);
	}

	#[test]
	fn report_store_round_trips_issue_rows() {
		let root = tempdir().unwrap();
		let store = TelemetryIndex::open(root.path(), &root.path().join("telemetry.sqlite")).unwrap();
		let issue = StoredIssue {
			id:                 sf!("i"),
			session_id:         sf!("s"),
			device:             sf!("read"),
			rev:                Some(sf!("2")),
			consent:            sf!("local_only"),
			created_at_ms:      1,
			payload_offset:     0,
			payload_len:        0,
			consent_revision:   None,
			attempt_count:      0,
			next_attempt_at_ms: 0,
			terminal:           false,
			remote_ack:         None,
		};
		store.store_issue(&issue).unwrap();
		assert_eq!(store.issue("i").unwrap(), Some(issue));
	}
}
